// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'addBtn': string;
  'collapsed': string;
  'collapsibleWrapper': string;
  'content': string;
  'contentAnswerWrapper': string;
  'empty': string;
  'growItem': string;
  'header': string;
  'headerWrapper': string;
  'items': string;
  'label': string;
  'left': string;
  'lineWrapper': string;
  'questionHeader': string;
  'questionWrapper': string;
  'refTitle': string;
  'right': string;
  'tag': string;
  'warning': string;
}
declare var cssExports: CssExports;
export = cssExports;
